// <auto-generated />
namespace PoliticList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class feedLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feedLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "201608152044164_feedLinks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
