// <auto-generated />
namespace PoliticList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class linkFeedCommentsUpdateAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linkFeedCommentsUpdateAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "201608180047205_linkFeedCommentsUpdateAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
